# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCacheEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid4', models.CharField(max_length=32)),
                ('screen_name', models.CharField(max_length=128)),
                ('following', models.PositiveIntegerField()),
            ],
        ),
    ]
